### ISSUE TITLE
Failed to build

### ISSUE THREAD

**Issue by kunalransing** [NEMPH/nem-apps-lib#10]
when try to build it give below errors:

[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 0.407 s
[INFO] Finished at: 2018-04-04T16:59:14+05:30
[INFO] Final Memory: 8M/303M
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal on project nem-apps-lib: Could not resolve dependencies for project io.nem.apps:nem-apps-lib:jar:0.0.1-SNAPSHOT: The following artifacts could not be resolved: org.nem.core:nem-core:jar:0.6.93-BETA, org.nem.core:nem-core:jar:tests:0.6.93-BETA: Failure to find org.nem.core:nem-core:jar:0.6.93-BETA in https://repo.maven.apache.org/maven2 was cached in the local repository, resolution will not be reattempted until the update interval of central has elapsed or updates are forced -> [Help 1]

**Comment by alvin-reyes** [comment]
You need to clone and build the nem.core library first.

**Comment by kunalransing** [comment]
Yes. Solved.

**Comment by BBLabPawanMaurya** [comment]
when i build ?

Step 1:  git clone https://github.com/NEMPH/nem.core.git
Step 2:  cd nem.core
Step 3:  mvn clean install

then I got this exception. What can I do  Please help! thanks

org.bouncycastle.crypto.InvalidCipherTextException: pad block corrupted
        at org.bouncycastle.crypto.paddings.PKCS7Padding.padCount(Unknown Source)
        at org.bouncycastle.crypto.paddings.PaddedBufferedBlockCipher.doFinal(Unknown Source)
        at org.nem.core.crypto.ed25519.Ed25519BlockCipher.transform(Ed25519BlockCipher.java:84)
        at org.nem.core.crypto.ed25519.Ed25519BlockCipher.decrypt(Ed25519BlockCipher.java:77)
        at org.nem.core.crypto.BlockCipherStressITCase.stressCipherSingleIteration(BlockCipherStressITCase.java:50)
        at org.nem.core.crypto.BlockCipherStressITCase.stressCipher(BlockCipherStressITCase.java:26)
        at org.nem.core.crypto.BlockCipherStressITCase.ed25519EngineCipherCannotBeCracked(BlockCipherStressITCase.java:12)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:47)
        at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
        at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:44)
        at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
        at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:271)
        at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:70)
        at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:50)
        at org.junit.runners.ParentRunner$3.run(ParentRunner.java:238)
        at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:63)
        at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:236)
        at org.junit.runners.ParentRunner.access$000(ParentRunner.java:53)
        at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:229)
        at org.junit.runners.ParentRunner.run(ParentRunner.java:309)
        at org.apache.maven.surefire.junit4.JUnit4Provider.execute(JUnit4Provider.java:264)
        at org.apache.maven.surefire.junit4.JUnit4Provider.executeTestSet(JUnit4Provider.java:153)
        at org.apache.maven.surefire.junit4.JUnit4Provider.invoke(JUnit4Provider.java:124)
        at org.apache.maven.surefire.booter.ForkedBooter.invokeProviderInSameClassLoader(ForkedBooter.java:200)
        at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:153)
        at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:103)
